# These are supported funding model platforms

# Enable GitHub Sponsors by adding your GitHub username or organization name
github: [Ilikejavaccpp]

# Add FOSS United using a custom URL link
custom: ['https://fossunited.org']
